AWSTemplateFormatVersion: 2010-09-09
Description: #<<Give description for this stack>>

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain 
    Properties:
      BucketName: #<<Name of the bucket here>>
      VersioningConfiguration:
        Status: Enabled 
      Tags:                                             
        - Key: #<<Tag key>>
          Value: #<<Value for the respective key>>

Outputs:
  MyBucket:  
    Description: #<<Reference for the s3 bucket created>>
    Export:
      Name: !Sub ${AWS::StackName}::MyBucket
    Value: !Sub ${CodePipelineArtifactStore}

  MyBucketArn:                          
    Description: #<<Ref of created S3 bucket's ARN>>
    Export:
      Name: !Sub ${AWS::StackName}::MyBucketArn
    Value:
      Fn::GetAtt: MyBucket.Arn
